### ISSUE TITLE
Kein Breadcrumb - Benutzerkonto mit Fehlermeldung

### ISSUE THREAD

**Issue by Anke** [terminal42/contao-zz_bebreadcrumb#10]
Hallo Andreas,

ich habe diese Erweiterung eben unter 3.5.24 installiert, aber mir wurde kein Breadcrumb angezeigt. Habe gewechselt zwiscchen default und flexible Template - trotzdem kein Breadcrumb sichtbar.

Changelanguage, haste und namespaceclassloader testweise deaktiviert, ebenfalls Easy_Themes - auch das ergab keine Änderung.

Beim Aufruf meines Benutzerkontos in der oberen Menüleiste erscheint folgender Fehler:

```
Fatal error: Uncaught exception Exception with message The table name must not be empty thrown in system/modules/core/library/Contao/DcaLoader.php on line 48

#0 system/modules/core/library/Contao/Controller.php(1297): Contao\DcaLoader->__construct(NULL)
#1 system/modules/zz_bebreadcrumb/BackendBreadcrumb.php(45): Contao\Controller::loadDataContainer(NULL)
#2 system/modules/core/classes/BackendTemplate.php(115): BackendBreadcrumb->generate('...', 'be_main')
#3 system/modules/core/controllers/BackendMain.php(275): Contao\BackendTemplate->output()
#4 system/modules/core/controllers/BackendMain.php(135): Contao\BackendMain->output()
#5 contao/main.php(20): Contao\BackendMain->run()
#6 {main}

```

Kannst du damit was anfangen? Brauchst du noch mehr Infos?

Ergänzungen: 
a) Webdeveloper sagt "TypeError: document.id(...) is null" in zz_bebreadcrumb.js Zeile 9
b) Ich nutze Easy_Themes als DOM-Objekt mit Kurzanzeige, und das wird durch zz_bebreadcrumb zerschossen bzw. deplaziert

**Comment by aschempp** [comment]
Die letzte Version dieser Erweiterung ist von 2014 (!!). Scheint als funktioniert sie mit Contao 3.5 nicht korrekt. Da wir sie selber nicht einsetzen kann ich leider keine Zeit für Bugfixes aufwenden. Ideal wäre du bezahlst einen Entwickler dafür den Fehler zu beheben, welcher die Anpassung dann per Pull Request zurückgeben kann :-)
