### ISSUE TITLE
Contao 3.3.x addToUrl Konflikt

### ISSUE THREAD

**Issue by e-spin** [terminal42/contao-zz_bebreadcrumb#7]
Hallo Andreas,
kannst Du noch ein namespace spendieren? die addToUrl kommt mit der Core-Methode ins gehege

**Comment by aschempp** [comment]
mehr Infos? Fehlermeldung?

**Comment by e-spin** [comment]
Contao 3.3.3

```
Runtime notice: Declaration of BackendBreadcrumb::addToUrl() should be compatible with Contao\System::addToUrl($strRequest) in C:\Users\meins\Contao2Go_v2\htdocs\vhosts\C-3-3_FD\system\modules\zz_bebreadcrumb\BackendBreadcrumb.php on line 253

#0 C:\Users\meins\Contao2Go_v2\htdocs\vhosts\C-3-3_FD\system\modules\core\library\Contao\ClassLoader.php(152): __error(2048, 'Declaration of ...', 'C:\Users\Samsun...', 253, Array)
#1 C:\Users\meins\Contao2Go_v2\htdocs\vhosts\C-3-3_FD\system\modules\core\library\Contao\ClassLoader.php(152): Contao\ClassLoader::load()
#2 [internal function]: Contao\ClassLoader::load('BackendBreadcru...')
#3 [internal function]: spl_autoload_call('BackendBreadcru...')
#4 C:\Users\meins\Contao2Go_v2\htdocs\vhosts\C-3-3_FD\system\modules\core\library\Contao\System.php(122): get_class_methods('BackendBreadcru...')
#5 C:\Users\meins\Contao2Go_v2\htdocs\vhosts\C-3-3_FD\system\modules\core\classes\BackendTemplate.php(115): Contao\System->import('BackendBreadcru...')
#6 C:\Users\meins\Contao2Go_v2\htdocs\vhosts\C-3-3_FD\contao\main.php(284): Contao\BackendTemplate->output()
#7 C:\Users\meins\Contao2Go_v2\htdocs\vhosts\C-3-3_FD\contao\main.php(146): Main->output()
#8 C:\Users\meins\Contao2Go_v2\htdocs\vhosts\C-3-3_FD\contao\main.php(293): Main->run()
#9 {main}
```

**Comment by math-GH** [comment]
Hallo @aschempp , ich verwende Contao 2.3 und zz_breadcrumbs 2.0.1. Gibt es in naher Zukunft ein Bugfix, oder muss ich auf diese tolle Erweiterung verzichten?
